In [1]:
import numpy as np

In [18]:
matriz =np.loadtxt("./dados/dados_artificiais.txt",skiprows=1, usecols=(1,2,3) )

In [19]:
matriz

array([[ 1.788811, 65.648102,  0.      ],
       [ 1.566784, 76.642768,  0.      ],
       [ 2.092193, 55.468185,  1.      ],
       [ 1.782471, 67.281997,  1.      ],
       [ 1.735767, 69.289008,  0.      ],
       [ 1.686975, 56.840051,  0.      ],
       [ 1.797105, 65.208973,  1.      ],
       [ 1.187349, 48.164764,  0.      ],
       [ 1.595891, 45.410648,  1.      ],
       [ 1.396282, 67.930113,  0.      ],
       [ 1.606148, 67.719604,  0.      ],
       [ 1.70759 , 45.609333,  0.      ],
       [ 1.735513, 64.845452,  0.      ],
       [ 1.672055, 39.705952,  1.      ],
       [ 1.723377, 50.05888 ,  1.      ],
       [ 1.684574, 56.545087,  1.      ],
       [ 1.733259, 37.512188,  0.      ],
       [ 1.7579  , 57.362422,  0.      ],
       [ 1.913338, 69.307246,  1.      ],
       [ 1.456048, 69.342337,  0.      ]])

Agora utilize esta matriz para calcular o IMC, utilizando a equação

```
IMC = peso / altura**2
```
e insira na nova tabela

In [20]:
calc_imc = [matriz[i][1]/(matriz[i][0]**2)  for i in range(len(matriz))]
calc_imc

[20.516026942563006,
 31.221439684559105,
 12.671862911844382,
 21.176487571306087,
 22.9975456097574,
 19.972717793575036,
 20.191122114932906,
 34.16431008742802,
 17.829996098895624,
 34.84304150287812,
 26.250844980187235,
 15.641792322967879,
 21.52899612253168,
 14.202163088357656,
 16.854681239064504,
 19.925750579824385,
 12.486636478786007,
 18.56261460033422,
 18.931945612244615,
 32.707480416323556]

In [21]:
imc_list = list()
for pessoa in matriz:
    peso = pessoa[1]
    altura = pessoa[0]
    IMC = (peso/altura**2)
    imc_list.append(IMC)

imc_array = np.array(imc_list)

new_table = np.concatenate((matriz, imc_array.reshape(-1,1)), axis=1)

new_table

array([[ 1.788811  , 65.648102  ,  0.        , 20.51602694],
       [ 1.566784  , 76.642768  ,  0.        , 31.22143968],
       [ 2.092193  , 55.468185  ,  1.        , 12.67186291],
       [ 1.782471  , 67.281997  ,  1.        , 21.17648757],
       [ 1.735767  , 69.289008  ,  0.        , 22.99754561],
       [ 1.686975  , 56.840051  ,  0.        , 19.97271779],
       [ 1.797105  , 65.208973  ,  1.        , 20.19112211],
       [ 1.187349  , 48.164764  ,  0.        , 34.16431009],
       [ 1.595891  , 45.410648  ,  1.        , 17.8299961 ],
       [ 1.396282  , 67.930113  ,  0.        , 34.8430415 ],
       [ 1.606148  , 67.719604  ,  0.        , 26.25084498],
       [ 1.70759   , 45.609333  ,  0.        , 15.64179232],
       [ 1.735513  , 64.845452  ,  0.        , 21.52899612],
       [ 1.672055  , 39.705952  ,  1.        , 14.20216309],
       [ 1.723377  , 50.05888   ,  1.        , 16.85468124],
       [ 1.684574  , 56.545087  ,  1.        , 19.92575058],
       [ 1.733259  , 37.

In [22]:
imc = np.array([peso/altura**2 for altura,peso,sexo in matriz])
imc = imc.reshape(20,1)
imc

array([[20.51602694],
       [31.22143968],
       [12.67186291],
       [21.17648757],
       [22.99754561],
       [19.97271779],
       [20.19112211],
       [34.16431009],
       [17.8299961 ],
       [34.8430415 ],
       [26.25084498],
       [15.64179232],
       [21.52899612],
       [14.20216309],
       [16.85468124],
       [19.92575058],
       [12.48663648],
       [18.5626146 ],
       [18.93194561],
       [32.70748042]])

| IMC             | Categoria           |   |
|-----------------|---------------------|---|
| abaixo de 16,00 | Baixo peso Grau III |   |
| 16,00 a 16,99   | Baixo peso Grau II  |   |
| 17,00 a 18.49   | Baixo peso Grau I   |   |
| 18,50 a 24,99   | Peso ideal          |   |
| 25,00 a 29,99   | Sobrepeso           |   |
| 30,00 a 34,99   | Obesidade Grau I    |   |
| 35,00 a 39,99   | Obesidade Grau II   |   |
| 40,0 e acima    | Obesidade Grau III  |   |

Agora utilize a tabela acima para indicar a qual categoria cada valor de IMC se enquadra. Insira novamente na tabela.

In [23]:
#Caio
category_list = []
for pessoa in new_table:
    imc = pessoa[-1]
    if imc < 16:
        category_list.append('Baixo peso Grau III')
    elif imc >= 16 and imc < 16.99:
        category_list.append('Baixo peso Grau II')
    elif imc >= 17 and imc < 18.49:
        category_list.append('Baixo peso Grau I')
    elif imc >= 18.5 and imc < 24.99:
        category_list.append('Peso ideal')
    elif imc >= 25 and imc < 29.99:
        category_list.append('Sobrepeso')
    elif imc >= 30 and imc < 34.99:
        category_list.append('Obesidade GRAU I')
    elif imc >= 35 and imc < 39.99:
        category_list.append('Obesidade GRAU II')
    elif imc >= 40:
        category_list.append('Obesidade GRAU III')

category_array = np.array(category_list)
final_table = np.concatenate((new_table, category_array.reshape(-1,1)), axis=1)

final_table

array([['1.788811', '65.648102', '0.0', '20.516026942563006',
        'Peso ideal'],
       ['1.566784', '76.642768', '0.0', '31.221439684559105',
        'Obesidade GRAU I'],
       ['2.092193', '55.468185', '1.0', '12.671862911844382',
        'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', '21.176487571306087',
        'Peso ideal'],
       ['1.735767', '69.289008', '0.0', '22.9975456097574', 'Peso ideal'],
       ['1.686975', '56.840051', '0.0', '19.972717793575036',
        'Peso ideal'],
       ['1.797105', '65.208973', '1.0', '20.191122114932906',
        'Peso ideal'],
       ['1.187349', '48.164764', '0.0', '34.16431008742802',
        'Obesidade GRAU I'],
       ['1.595891', '45.410648', '1.0', '17.829996098895624',
        'Baixo peso Grau I'],
       ['1.396282', '67.930113', '0.0', '34.84304150287812',
        'Obesidade GRAU I'],
       ['1.606148', '67.719604', '0.0', '26.250844980187235',
        'Sobrepeso'],
       ['1.70759', '45.609333', '0.0', '15.6

In [24]:
# Dário
categoria = []
for imc in calc_imc:
    if imc < 16:
        categoria.append('Baixo peso Grau III')
    elif imc <= 16.99:
        categoria.append('Baixo peso Grau II')
    elif imc <= 18.49:
        categoria.append('Baixo peso Grau I')
    elif imc <= 24.99:
        categoria.append('Peso ideal')
    elif imc <= 29.99:
        categoria.append('Sobrepeso')
    elif imc <= 34.99:
        categoria.append('Obesidade Grau I')
    elif imc <= 39.99:
        categoria.append('Obesidade Grau II')
    else:
        categoria.append('Obesidade Grau III')
        
categoria = np.array(categoria).reshape((len(categoria)), 1)

matriz_final = np.append(matriz, categoria, axis=1)
matriz_final

array([['1.788811', '65.648102', '0.0', 'Peso ideal'],
       ['1.566784', '76.642768', '0.0', 'Obesidade Grau I'],
       ['2.092193', '55.468185', '1.0', 'Baixo peso Grau III'],
       ['1.782471', '67.281997', '1.0', 'Peso ideal'],
       ['1.735767', '69.289008', '0.0', 'Peso ideal'],
       ['1.686975', '56.840051', '0.0', 'Peso ideal'],
       ['1.797105', '65.208973', '1.0', 'Peso ideal'],
       ['1.187349', '48.164764', '0.0', 'Obesidade Grau I'],
       ['1.595891', '45.410648', '1.0', 'Baixo peso Grau I'],
       ['1.396282', '67.930113', '0.0', 'Obesidade Grau I'],
       ['1.606148', '67.719604', '0.0', 'Sobrepeso'],
       ['1.70759', '45.609333', '0.0', 'Baixo peso Grau III'],
       ['1.735513', '64.845452', '0.0', 'Peso ideal'],
       ['1.672055', '39.705952', '1.0', 'Baixo peso Grau III'],
       ['1.723377', '50.05888', '1.0', 'Baixo peso Grau II'],
       ['1.684574', '56.545087', '1.0', 'Peso ideal'],
       ['1.733259', '37.512188', '0.0', 'Baixo peso Grau III'],