In [1]:
import numpy as np

### Exercício:
1. Dado o array X = np.array(['A','B','C','D','E'])
Mostre o último elemento
2. Mostre os primeiros 3 elementos
3. Mostre só os elementos do meio
4. Inverta a ordem do array
5. Mostre os elementos nas posições impar.
6. De acordo com a matriz, mostre a primeira linha X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
7. Mostre o primeiro elemento na primeira linha
8. Mostre a linha intermediária
9. Os primeiros 2 elementos das duas primeiras linhas
10. Os últimos 2 elementos das duas últimas linhas

In [101]:
X =np.array(['A','B','C','D','E'])
print(X[-1])

E


In [85]:
print(X[0:3])

['A' 'B' 'C']


In [87]:
print(X[1:4])

['B' 'C' 'D']


In [102]:
print(X[::-1])

['E' 'D' 'C' 'B' 'A']


In [103]:
print(X[1:len(X):2])

['B' 'D']


In [105]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(X[0])


[1 2 3 4]


In [106]:
print(X[0,0])

1


In [107]:
print(X[2])

[ 9 10 11 12]


In [112]:
print(X[0][0:2])
print(X[1][0:2])

[1 2]
[5 6]


In [120]:
print(X[-2][-2:len(X)])
print(X[-1][-2:len(X)])

[11 12]
[15 16]


### Exercicios:
1. De acordo com o array X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
faça a soma
2. Faça a média
3. Dada a matriz faça a soma das colunas X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
4. Faça a média das linhas
5. Dado o array X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
Mostre o elemento de maior valor

In [122]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

print(np.sum(X))

43


In [123]:
print(np.sum(X)/len(X))

4.777777777777778


In [125]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print(np.sum(X, axis=0))


[28 32 36 40]


In [127]:
print(np.sum(X, axis=1)/len(X))

[ 2.5  6.5 10.5 14.5]


In [128]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

print(np.max(X))

10
