In [1]:
import numpy as np

### Exercicio:
1. Crie um array numpy com valores partindo de 10 até 49
2. Crie uma matriz numpy de 2 por 2 preenchida com 1's
3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's
4. Crie uma matriz 4 por 4 de integers preenchida com 5's
5. Crie uma matriz identidade de 3 por 3
6. Crie um array numppy prrenchido 3 integers aleatórias entre 1 e 10


In [3]:
X = np.arange(10, 50)
X

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
M = np.ones(shape=(2,2))
M

array([[1., 1.],
       [1., 1.]])

In [6]:
M = np.ones(shape=(3,2), dtype=np.float64)
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
M = np.full(shape=(4,4), fill_value=5, dtype=np.int64)
M

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int64)

In [16]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
r = np.random.randint(1, 10, 3)
r

array([3, 4, 8])